swagger: "2.0"
info:
  title: Spin API service
  description: HTTP service for controlling the spin service
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{id}:
    post:
      tags:
      - spin-broker
      summary: add spin-broker
      operationId: spin-broker#add
      parameters:
      - name: id
        in: path
        description: queue ID
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinBrokerAddRequestBody'
          required:
          - resource
          - action
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /complete:
    post:
      tags:
      - spin-broker
      summary: complete spin-broker
      operationId: spin-broker#complete
      parameters:
      - name: CompleteRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinBrokerCompleteRequestBody'
          required:
          - id
          - status
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /enqueue/{id}:
    post:
      tags:
      - spin-broker
      summary: enqueue spin-broker
      operationId: spin-broker#enqueue
      parameters:
      - name: id
        in: path
        description: queue ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Aut non dicta quisquam rem qui ut.
      schemes:
      - http
  /new:
    post:
      tags:
      - spin-broker
      summary: new spin-broker
      operationId: spin-broker#new
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /next/{resource}:
    get:
      tags:
      - spin-broker
      summary: next spin-broker
      operationId: spin-broker#next
      parameters:
      - name: resource
        in: path
        description: resource type
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinBrokerNextResponseBody'
            required:
            - resource
            - action
      schemes:
      - http
  /status/{id}:
    get:
      tags:
      - spin-broker
      summary: status spin-broker
      operationId: spin-broker#status
      parameters:
      - name: id
        in: path
        description: queue ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinBrokerStatusResponseBody'
            required:
            - status
      schemes:
      - http
definitions:
  SpinBrokerAddRequestBody:
    title: SpinBrokerAddRequestBody
    type: object
    properties:
      action:
        type: string
        description: Action name
        example: Vitae sunt amet nostrum amet.
      parameters:
        type: array
        items:
          type: string
          example: Itaque dolorem odio.
        description: Action parameters
        example:
        - Et rerum ut voluptatem.
        - Fugit fuga impedit dolor.
        - Quo non.
      resource:
        type: string
        description: Resource name
        example: Ipsam dolor distinctio.
    example:
      action: Labore qui nobis.
      parameters:
      - Dolor assumenda voluptatem dignissimos.
      - Doloremque harum et tempora.
      - Qui quia.
      resource: Rerum officia iusto minima.
    required:
    - resource
    - action
  SpinBrokerCompleteRequestBody:
    title: SpinBrokerCompleteRequestBody
    type: object
    properties:
      id:
        type: string
        description: queue ID
        example: Non aut molestiae deleniti ad dolorem eos.
      status:
        type: boolean
        description: status of work
        example: false
      status_reason:
        type: string
        description: reason of success/failure
        example: Adipisci est incidunt sequi.
    example:
      id: Maxime aut non.
      status: false
      status_reason: Nostrum commodi error omnis quis quia.
    required:
    - id
    - status
  SpinBrokerNextResponseBody:
    title: SpinBrokerNextResponseBody
    type: object
    properties:
      action:
        type: string
        description: action name
        example: Ullam amet magnam.
      parameters:
        type: array
        items:
          type: string
          example: Ad ut nulla laboriosam non deserunt vitae.
        description: parameters for action
        example:
        - Sint ducimus ullam odio.
        - Aliquid consequatur atque quam neque.
        - Id et autem ut debitis.
        - Saepe occaecati impedit quas laborum.
      resource:
        type: string
        description: resource type
        example: Dolor nesciunt omnis.
    example:
      action: Voluptatem quibusdam dolor.
      parameters:
      - Porro fugiat ex consequatur provident dignissimos.
      - Possimus velit quod sit.
      - Mollitia natus temporibus fugit occaecati ipsum qui.
      resource: Quaerat itaque aut.
    required:
    - resource
    - action
  SpinBrokerStatusResponseBody:
    title: SpinBrokerStatusResponseBody
    type: object
    properties:
      status:
        type: boolean
        description: Pass/Fail status
        example: false
    example:
      status: false
    required:
    - status
