openapi: 3.0.3
info:
  title: Spin API service
  description: HTTP service for controlling the spin service
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /add/{id}:
    post:
      tags:
      - spin-broker
      summary: add spin-broker
      operationId: spin-broker#add
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        schema:
          type: string
          description: Package ID
          example: Dicta id sint rerum rerum.
        example: Eius officiis esse labore voluptas perferendis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              action: Temporibus ipsa quibusdam nostrum.
              parameters:
              - Est officia.
              - Est esse similique officiis.
              - Saepe voluptatum dolorem rerum et vel.
              - Maxime corrupti molestias est sunt ab repellat.
              resource: Sint quisquam ducimus autem consequatur reprehenderit.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Consequatur quo exercitationem occaecati magnam molestiae
                  qui.
              example: Iusto adipisci sapiente temporibus.
  /complete:
    post:
      tags:
      - spin-broker
      summary: complete spin-broker
      operationId: spin-broker#complete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteRequestBody'
            example:
              id: Quibusdam reiciendis ipsum commodi.
              status: true
              status_reason: Consequatur sunt.
      responses:
        "200":
          description: OK response.
  /enqueue/{id}:
    post:
      tags:
      - spin-broker
      summary: enqueue spin-broker
      operationId: spin-broker#enqueue
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        schema:
          type: string
          description: Package ID
          example: Aut minima recusandae et.
        example: Fugit quis.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Iure aut voluptas qui.
                example:
                - Inventore cupiditate soluta ut corporis sit.
                - Sit recusandae eum repellat.
                - Provident sint.
                - Hic minus facere animi quas tempora.
              example:
              - Error modi magni voluptas corrupti et.
              - Et et occaecati.
              - Quo dolore soluta consectetur.
  /new:
    post:
      tags:
      - spin-broker
      summary: new spin-broker
      operationId: spin-broker#new
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Ratione et ex tempore ipsum in.
              example: Vero amet quia quis omnis suscipit est.
  /next/{resource}:
    get:
      tags:
      - spin-broker
      summary: next spin-broker
      operationId: spin-broker#next
      parameters:
      - name: resource
        in: path
        description: resource type
        required: true
        schema:
          type: string
          description: resource type
          example: Et nobis quia neque excepturi.
        example: Expedita a.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddRequestBody'
              example:
                action: Eum officiis eligendi.
                parameters:
                - Qui ipsum.
                - Voluptatibus quis at distinctio.
                resource: Non deleniti consequuntur qui doloremque.
  /status/{id}:
    get:
      tags:
      - spin-broker
      summary: status spin-broker
      operationId: spin-broker#status
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        schema:
          type: string
          description: Package ID
          example: Quia non nihil vitae nesciunt.
        example: Assumenda pariatur.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponseBody'
              example:
                status: true
components:
  schemas:
    AddRequestBody:
      type: object
      properties:
        action:
          type: string
          description: Action name
          example: Consectetur et.
        parameters:
          type: array
          items:
            type: string
            example: Vero alias doloribus impedit impedit qui dolor.
          description: Action parameters
          example:
          - Non ut hic.
          - Assumenda ullam qui et.
          - Qui voluptate sunt itaque tenetur labore quia.
          - Aperiam nobis soluta voluptatem.
        resource:
          type: string
          description: Resource name
          example: Et maiores ut voluptatem sed.
      example:
        action: Iste illum omnis.
        parameters:
        - Repellendus eaque nesciunt quia.
        - Neque reiciendis ipsum.
        resource: Natus non consequatur voluptatem nostrum.
      required:
      - resource
      - action
    CompleteRequestBody:
      type: object
      properties:
        id:
          type: string
          description: Command ID
          example: Deserunt qui praesentium temporibus esse.
        status:
          type: boolean
          description: status of work
          example: true
        status_reason:
          type: string
          description: reason of success/failure
          example: Molestias eum voluptatem qui nihil officia.
      example:
        id: Vel vel illum voluptatem voluptatibus.
        status: false
        status_reason: Cum delectus occaecati enim in.
      required:
      - id
      - status
    StatusResponseBody:
      type: object
      properties:
        status:
          type: boolean
          description: Pass/Fail status
          example: true
      example:
        status: false
      required:
      - status
